### ISSUE TITLE
Question,please

### ISSUE THREAD

**Issue by 1009177062** [amedwards/NICUHDF5Viewer#1]
I don't understand a lot of things when I look at the code. Can you talk about the architecture of the code?

**Comment by amedwards** [comment]
This code was written for a specific HDF5 file architecture for a multisite study. If you are part of the PreVent study team, please review the wiki on UVA collab which has a detailed overview of the code. Unfortunately, I am not able to reply further as I am currently on maternity leave.

**Comment by amedwards** [comment]
I have begun migrating the wiki from UVA Collab to this github repository. Please see the wiki here: [https://github.com/amedwards/NICUHDF5Viewer.wiki.git](url)

If you are a member of PreVent, please let me know if there are further questions I can answer.
